### ISSUE TITLE
error  in new release of mxnet-ssd amalgamation

### ISSUE THREAD

**Issue by nopattern** [zhreshold/mxnet-ssd.cpp#11]
hi,@zhreshold 
   I have used your new release of mxnet-ssd/mxnet/amalgamation and use following command. 
   `./ssd ../demo/000001.jpg`
then the error occured:

> [04:21:39] mxnet_predict-all.cc:634: [04:21:39] mxnet_predict-all.cc:23298: Check failed: op != nullptr Operator L2Normalization is not registered
> Segmentation fault

**Comment by zhreshold** [comment]
Seems like the amalgamation makefile hasn't been updated for quite a long time. 
Adding operator source file to the makefile might solve it, but I'm not quite sure how it works right now.

**Comment by nopattern** [comment]
Sovled by adding operator source. Thank you .
