### ISSUE TITLE
Option to exit the exe when computation ends

### ISSUE THREAD

**Issue by ShakedDovratt** [zhreshold/mxnet-ssd.cpp#3]
Hi,

Thank you for this standalone distribution, I find it helpful.

I'm trying to run the exe on many images sequentually. I use the output to file option (`-o`), but after computation of each image the window remains open, and my script is blocked until I close the window manually. I can't process a large batch that way. Running in background doesn't cut it because it then runs multiple images at once and eventually crashes my computer.

I'm missing a flag saying "close the program after computation (and output to file/s) ends". It sounds like an easy task to do and will help me a lot.

Thanks.

**Comment by zhreshold** [comment]
You can use --disp-size=-1 to disable display at all.
