### ISSUE TITLE
mobile transport problem

### ISSUE THREAD

**Issue by nopattern** [zhreshold/mxnet-ssd.cpp#9]
Hi,@zhreshold , There's amalgamation directory in mxnet-ssd/mxnet which seems to be for mobile devices. I also find you have made a project named 'mxnet-ssd.cpp' ,which is good for transportation to mobile device?

**Comment by zhreshold** [comment]
You could try mxnet/amalgamation first, if not success, refer to mxnet-ssd.cpp for minimum functionality.

**Comment by nopattern** [comment]
thanks a lot.
